Update gp_module_two.md
   This Code block is missing `ClientNetworkVariable`. Since it is not defined unity throws following error:
  `Assets/Scripts/NetworkVariableTest.cs(28,19): error CS0103: The name 'ClientNetworkVariable' does not exist in the current context`